apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: petclinic
  labels:
    applicationName: petclinic
spec:
  selector:
    matchLabels:
      applicationName: petclinic
  replicas: 3 
  template: 
    metadata:
      labels:
        applicationName: petclinic
    spec:
      containers:
      - name: petclinic
        image: rdarst/petclinic-spinnaker-jenkins
        ports:
        - containerPort: 8080
        imagePullPolicy: Always

